version: "3"

services:
  app:
    build: .
    volumes:
      - ".:/app"
    env_file: .env
    command: >
      sh -c '
        curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /go/bin \
        && air
      '
